name: Production Stage Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false
      - name: Install Dependencies
        run: |
          poetry install
      - name: Security check with bandit
        run: |
          poetry run bandit -c pyproject.toml -r .
      - name: Lint with Ruff
        run: |
          poetry run ruff check
      - name: Check formatting with black
        run: |
          poetry run black --check .
      - name: Test with pytest and coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report
          poetry run coverage xml

  create-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        with: 
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  notify: 
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/actions-send-mail@v3
        with: 
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: New Release Created
          to: joshua.andersland@gmail.com
          from: CI/CD <josh.andersland@gmail.com>
          body: A new release has been created.